version: '3.7'

services:
  web:
    build: .
    environment:
      - SECRET_KEY=tp5q!!c=uq5ko%u=+)9xu0@tpv@s7@teipxv1v4p$c*#eiqzj@
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    user: ${CURRENT_UID}
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: