version: '3.7'

services:
  web:
    build: .
    env_file:
      - .env.prod
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    user: ${CURRENT_UID}
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

volumes:
  postgres_data: